---
abstract: 'basic wireless library for perl, based on wireless-tools'
author:
  - 'Edoardo Mantovani, aka BASEBAND <BASEBAND_at_cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Air-Wireless
no_index:
  directory:
    - t
    - inc
requires:
  perl: '0'
version: '0.7'
